### ISSUE TITLE
Export information to PDF

### ISSUE THREAD

**Issue by Zitorrr** [ARRCE00/GESPRO_Practica_2_Curso_2024_2025#14]
Related with #9

**Comment by Zitorrr** [comment]
¿Cómo se exportaria a PDF?

**Comment by Davidsantamaria1111** [comment]
> ¿Cómo se exportaria a PDF?

Utilizaría una biblioteca como jsPDF (en frontend) o ReportLab (en backend) para generar el PDF, extrayendo la información necesaria y formateándola antes de exportarla con un botón de "Descargar PDF".
