### ISSUE TITLE
Manage the app form an iPhone

### ISSUE THREAD

**Issue by Zitorrr** [ARRCE00/GESPRO_Practica_2_Curso_2024_2025#3]
Related with #2

**Comment by Davidsantamaria1111** [comment]
¿Como gestionas la aplicación desde un iPhone?

**Comment by Zitorrr** [comment]
> ¿Como gestionas la aplicación desde un iPhone?

Descargando la app desde el App Store y accediendo con tus credenciales para gestionar funciones como transferencias, ajustes y consultas de saldo.
